export const STAT_DESIRED_KEYS = [
  "Troop Attack",
  "Troop Health",
  "Troop Defense",
  "Troop Damage",
  "Troop Damage Received",
  "Troop Attack Blessing",
  "Troop Protection Blessing",
  "Archer Attack",
  "Archer Health",
  "Archer Defense",
  "Archer Damage",
  "Archer Damage Received",
  "Archer Attack Blessing",
  "Archer Protection Blessing",
  "Cavalry Attack",
  "Cavalry Health",
  "Cavalry Defense",
  "Cavalry Damage",
  "Cavalry Damage Received",
  "Cavalry Attack Blessing",
  "Cavalry Protection Blessing",
  "Siege Attack",
  "Siege Health",
  "Siege Defense",
  "Siege Damage",
  "Siege Damage Received",
  "Siege Attack Blessing",
  "Siege Protection Blessing",
  "Lethal Hit Rate",
];

export const statOcrFixtures = [
  {
    id: "synthetic-full-stat-page",
    description:
      "Synthetic OCR text shaped like a full stat screenshot. No real player or alliance data.",
    rawText: [
      "Troop Attack",
      "412.8%",
      "Troop Health 386.2%",
      "Troop Defense",
      "378.4%",
      "Troop Damage 32.5%",
      "Troop Damage Received 18.2%",
      "Troop Attack Blessing 22.1%",
      "Troop Protection Blessing",
      "19.7%",
      "Archer Attack 516.4%",
      "Archer Health",
      "442.6%",
      "Archer Defense 430.1%",
      "Archer Damage 41.3%",
      "Archer Damage Received",
      "20.5%",
      "Archer Attack Blessing 28.4%",
      "Archer Protection Blessing 24.2%",
      "Cavalry Attack 498.9%",
      "Cavalry Health 421.3%",
      "Cavalry Defense 405.7%",
      "Cavalry Damage 38.9%",
      "Cavalry Damage Received 19.8%",
      "Cavalry Attack Blessing",
      "26.1%",
      "Cavalry Protection Blessing 23.6%",
      "Siege Attack 455.2%",
      "Siege Health 399.5%",
      "Siege Defense 384.8%",
      "Siege Damage 35.4%",
      "Siege Damage Received 17.7%",
      "Siege Attack Blessing 21.5%",
      "Siege Protection Blessing 20.9%",
      "Lethal Hit Rate 12.4%",
    ].join("\n"),
    expectedParsed: {
      "Troop Attack": "412.8%",
      "Troop Health": "386.2%",
      "Troop Defense": "378.4%",
      "Troop Damage": "32.5%",
      "Troop Damage Received": "18.2%",
      "Troop Attack Blessing": "22.1%",
      "Troop Protection Blessing": "19.7%",
      "Archer Attack": "516.4%",
      "Archer Health": "442.6%",
      "Archer Defense": "430.1%",
      "Archer Damage": "41.3%",
      "Archer Damage Received": "20.5%",
      "Archer Attack Blessing": "28.4%",
      "Archer Protection Blessing": "24.2%",
      "Cavalry Attack": "498.9%",
      "Cavalry Health": "421.3%",
      "Cavalry Defense": "405.7%",
      "Cavalry Damage": "38.9%",
      "Cavalry Damage Received": "19.8%",
      "Cavalry Attack Blessing": "26.1%",
      "Cavalry Protection Blessing": "23.6%",
      "Siege Attack": "455.2%",
      "Siege Health": "399.5%",
      "Siege Defense": "384.8%",
      "Siege Damage": "35.4%",
      "Siege Damage Received": "17.7%",
      "Siege Attack Blessing": "21.5%",
      "Siege Protection Blessing": "20.9%",
      "Lethal Hit Rate": "12.4%",
    },
    atlantis: {
      archer: "7.5%",
      cavalry: "5%",
      siege: "0%",
    },
    expectedFinalDamage: {
      archer: "256.8",
      cavalry: "237.6",
      siege: "202.7",
    },
  },
];

export const reportOcrCleanupFixtures = [
  {
    id: "synthetic-report-row-noisy-ocr",
    description:
      "Documents the current report cleanup expectation after OCR: O/O becomes 0, punctuation is removed, and the first four values map to labels.",
    rawText: "12,O34 56.7 8,901 Survivors 2345 extra",
    expectedCleanValues: ["12034", "567", "8901", "0"],
    expectedEntry: {
      Kills: "12034",
      Losses: "567",
      Wounded: "8901",
      Survivors: "0",
    },
  },
];
