export const STAT_DESIRED_KEYS = [
  "Troop Attack",
  "Troop Health",
  "Troop Defense",
  "Troop Damage",
  "Troop Damage Received",
  "Troop Attack Blessing",
  "Troop Protection Blessing",
  "Archer Attack",
  "Archer Health",
  "Archer Defense",
  "Archer Damage",
  "Archer Damage Received",
  "Archer Attack Blessing",
  "Archer Protection Blessing",
  "Cavalry Attack",
  "Cavalry Health",
  "Cavalry Defense",
  "Cavalry Damage",
  "Cavalry Damage Received",
  "Cavalry Attack Blessing",
  "Cavalry Protection Blessing",
  "Siege Attack",
  "Siege Health",
  "Siege Defense",
  "Siege Damage",
  "Siege Damage Received",
  "Siege Attack Blessing",
  "Siege Protection Blessing",
  "Lethal Hit Rate",
];

export const statOcrFixtures = [
  {
    id: "synthetic-full-stat-page",
    description:
      "Synthetic OCR text shaped like a full stat screenshot. No real player or alliance data.",
    rawText: [
      "Troop Attack",
      "412.8%",
      "Troop Health 386.2%",
      "Troop Defense",
      "378.4%",
      "Troop Damage 32.5%",
      "Troop Damage Received 18.2%",
      "Troop Attack Blessing 22.1%",
      "Troop Protection Blessing",
      "19.7%",
      "Archer Attack 516.4%",
      "Archer Health",
      "442.6%",
      "Archer Defense 430.1%",
      "Archer Damage 41.3%",
      "Archer Damage Received",
      "20.5%",
      "Archer Attack Blessing 28.4%",
      "Archer Protection Blessing 24.2%",
      "Cavalry Attack 498.9%",
      "Cavalry Health 421.3%",
      "Cavalry Defense 405.7%",
      "Cavalry Damage 38.9%",
      "Cavalry Damage Received 19.8%",
      "Cavalry Attack Blessing",
      "26.1%",
      "Cavalry Protection Blessing 23.6%",
      "Siege Attack 455.2%",
      "Siege Health 399.5%",
      "Siege Defense 384.8%",
      "Siege Damage 35.4%",
      "Siege Damage Received 17.7%",
      "Siege Attack Blessing 21.5%",
      "Siege Protection Blessing 20.9%",
      "Lethal Hit Rate 12.4%",
    ].join("\n"),
    expectedParsed: {
      "Troop Attack": "412.8%",
      "Troop Health": "386.2%",
      "Troop Defense": "378.4%",
      "Troop Damage": "32.5%",
      "Troop Damage Received": "18.2%",
      "Troop Attack Blessing": "22.1%",
      "Troop Protection Blessing": "19.7%",
      "Archer Attack": "516.4%",
      "Archer Health": "442.6%",
      "Archer Defense": "430.1%",
      "Archer Damage": "41.3%",
      "Archer Damage Received": "20.5%",
      "Archer Attack Blessing": "28.4%",
      "Archer Protection Blessing": "24.2%",
      "Cavalry Attack": "498.9%",
      "Cavalry Health": "421.3%",
      "Cavalry Defense": "405.7%",
      "Cavalry Damage": "38.9%",
      "Cavalry Damage Received": "19.8%",
      "Cavalry Attack Blessing": "26.1%",
      "Cavalry Protection Blessing": "23.6%",
      "Siege Attack": "455.2%",
      "Siege Health": "399.5%",
      "Siege Defense": "384.8%",
      "Siege Damage": "35.4%",
      "Siege Damage Received": "17.7%",
      "Siege Attack Blessing": "21.5%",
      "Siege Protection Blessing": "20.9%",
      "Lethal Hit Rate": "12.4%",
    },
    atlantis: {
      archer: "7.5%",
      cavalry: "5%",
      siege: "0%",
    },
    expectedFinalDamage: {
      archer: "256.8",
      cavalry: "237.6",
      siege: "202.7",
    },
  },
  {
    id: "real-lord-info-2026-06-06-visible-stat-page",
    description:
      "Sanitized real Last Land: Empire Builder Lord Info screenshot values provided by the user. Player and alliance identity are intentionally omitted.",
    rawText: [
      "Infantry Damage 186.5%",
      "Infantry Damage Received -196.5%",
      "Infantry Attack Blessing 234%",
      "Infantry Protection Blessing 700%",
      "Cavalry Attack 2143%",
      "Cavalry Health 1348%",
      "Cavalry Defense 933%",
      "Cavalry Damage 197.75%",
      "Cavalry Damage Received -160.5%",
      "Cavalry Attack Blessing 588%",
      "Cavalry Protection Blessing 420%",
      "Archer Attack 2528.7%",
      "Archer Health 1527%",
      "Archer Defense 1320.7%",
      "Archer Damage 201.5%",
      "Archer Damage Received -175%",
      "Archer Attack Blessing 621%",
      "Archer Protection Blessing 376%",
      "Siege Attack 1638.35%",
      "Siege Health 931%",
      "Siege Defense 1326.5%",
      "Siege Damage 160%",
      "Siege Damage Received -160.5%",
      "Siege Attack Blessing 331%",
      "Siege Protection Blessing 159%",
      "Troop Attack 303.35%",
      "Troop Health 228.85%",
      "Troop Defense 296.85%",
      "Troop Damage 43.75%",
      "Troop Damage Received -43.75%",
      "Troop Attack Blessing 600%",
      "Troop Protection Blessing 473.08%",
      "Revive 26%",
      "Lethal Hit Rate 24%",
    ].join("\n"),
    expectedParsed: {
      "Troop Attack": "303.35%",
      "Troop Health": "228.85%",
      "Troop Defense": "296.85%",
      "Troop Damage": "43.75%",
      "Troop Damage Received": "43.75%",
      "Troop Attack Blessing": "600%",
      "Troop Protection Blessing": "473.08%",
      "Archer Attack": "2528.7%",
      "Archer Health": "1527%",
      "Archer Defense": "1320.7%",
      "Archer Damage": "201.5%",
      "Archer Damage Received": "175%",
      "Archer Attack Blessing": "621%",
      "Archer Protection Blessing": "376%",
      "Cavalry Attack": "2143%",
      "Cavalry Health": "1348%",
      "Cavalry Defense": "933%",
      "Cavalry Damage": "197.75%",
      "Cavalry Damage Received": "160.5%",
      "Cavalry Attack Blessing": "588%",
      "Cavalry Protection Blessing": "420%",
      "Siege Attack": "1638.35%",
      "Siege Health": "931%",
      "Siege Defense": "1326.5%",
      "Siege Damage": "160%",
      "Siege Damage Received": "160.5%",
      "Siege Attack Blessing": "331%",
      "Siege Protection Blessing": "159%",
      "Lethal Hit Rate": "24%",
    },
    atlantis: {
      archer: "0%",
      cavalry: "0%",
      siege: "0%",
    },
    expectedFinalDamage: {
      archer: "27053.5",
      cavalry: "22452.6",
      siege: "14606.3",
    },
  },
];

export const reportOcrCleanupFixtures = [
  {
    id: "synthetic-report-row-noisy-ocr",
    description:
      "Documents report cleanup after OCR: O/O becomes 0 only inside numeric-looking values, punctuation is removed, and the first four values map to labels.",
    rawText: "12,O34 56.7 8,901 Survivors 2345 extra",
    expectedCleanValues: ["12034", "567", "8901", "2345"],
    expectedEntry: {
      Kills: "12034",
      Losses: "567",
      Wounded: "8901",
      Survivors: "2345",
    },
  },
];
